### ISSUE TITLE
Did you remove PCR duplicates when processing single-cell riboseq data?

### ISSUE THREAD

**Issue by suluying** [mvanins/scRiboSeq_manuscript#1]
Hello, 
Thanks for developing this really interesting methodology. I have a question that did you remove PCR duplicates when processing single-cell riboseq data?

**Comment by mvanins** [comment]
Hi,

Yes, a 10-nt UMI is attached during the 5' adapter ligation. After alignment, reads are de-duplicated using UMI-tools; the specific settings are here https://github.com/mvanins/scRiboSeq_manuscript/blob/fc5579b299b1d0d5a5408d188d81532c3db2396a/data_processing/templates/deduplicate/deduplicate_position.sh#L1-L8
